# Generated by Django 4.2.11 on 2025-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("total_employees", models.IntegerField()),
                ("year_founded", models.IntegerField()),
                ("headquarters", models.CharField(max_length=255)),
                ("imported_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
