# Generated by Django 4.2.11 on 2025-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_company_headquarters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_saas",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_usa_based",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
